/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    'IAntDesign:fullscreenExitOutlined': typeof import('~icons/ant-design/fullscreen-exit-outlined')['default']
    'IAntDesign:fullscreenOutlined': typeof import('~icons/ant-design/fullscreen-outlined')['default']
    'IIc:outlineWbSunny': typeof import('~icons/ic/outline-wb-sunny')['default']
    'IIc:roundRefresh': typeof import('~icons/ic/round-refresh')['default']
    'ILineMd:githubLoop': typeof import('~icons/line-md/github-loop')['default']
    'ILineMd:moonAltToSunnyOutlineLoopTransition': typeof import('~icons/line-md/moon-alt-to-sunny-outline-loop-transition')['default']
    'ILineMd:sunnyFilledLoopToMoonAltFilledLoopTransition': typeof import('~icons/line-md/sunny-filled-loop-to-moon-alt-filled-loop-transition')['default']
    'IMdi:moonWaxingCrescent': typeof import('~icons/mdi/moon-waxing-crescent')['default']
    'ITabler:brandGithub': typeof import('~icons/tabler/brand-github')['default']
    'ITabler:indentDecrease': typeof import('~icons/tabler/indent-decrease')['default']
    'ITabler:indentIncrease': typeof import('~icons/tabler/indent-increase')['default']
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default']
    NaiveProviderContent: typeof import('./../src/components/common/NaiveProviderContent.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
